{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "362c4e1a-1f80-4f8f-a5f8-fb0e804a89ed",
   "metadata": {},
   "source": [
    "# Launch the MNE Qt-based EEG viewer with sample data"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "429d8d00-7cdb-4909-85cf-9a44f0e7df0b",
   "metadata": {},
   "source": [
    "1. Install the follwing from conda-forge:\n",
    "- `mne-base h5io h5py pymatreader jupyterlab pandas mne-qt-browser`"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "06948918-558a-4b58-bb12-c4c49f1eec3e",
   "metadata": {},
   "source": [
    "2. Download data\n",
    "- for example: `https://physionet.org/files/eegmmidb/1.0.0/S001/S001R04.edf?download`"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2eff652b-915d-4b9f-85d0-76f72adf0486",
   "metadata": {},
   "source": [
    "3. Read data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "16fadf8f-ad0f-4f6a-bb7b-9624e0b288fe",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'/Users/droumis/data/mne_data/S001R04.edf'"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "sample_data_raw_file = ('/Users/droumis/data/mne_data/S001R04.edf') # your path to data\n",
    "sample_data_raw_file"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "e848b88f-271f-4608-a1d3-9a76046e57b7",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "%gui qt5\n",
    "import mne"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "7ba5e861-c715-4c33-ac78-751354032b76",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Extracting EDF parameters from /Users/droumis/data/mne_data/S001R04.edf...\n",
      "EDF file detected\n",
      "Setting channel info structure...\n",
      "Creating raw.info structure...\n"
     ]
    }
   ],
   "source": [
    "raw = mne.io.read_raw_edf(sample_data_raw_file)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "3c91f539-941f-4b96-824e-0b2ac76058dc",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<table class=\"table table-hover table-striped table-sm table-responsive small\">\n",
       "    <tr>\n",
       "        <th>Measurement date</th>\n",
       "        \n",
       "        <td>August 12, 2009  16:15:00 GMT</td>\n",
       "        \n",
       "    </tr>\n",
       "    <tr>\n",
       "        <th>Experimenter</th>\n",
       "        \n",
       "        <td>Unknown</td>\n",
       "        \n",
       "    </tr>\n",
       "        <th>Participant</th>\n",
       "        \n",
       "        <td>Unknown</td>\n",
       "        \n",
       "    </tr>\n",
       "    <tr>\n",
       "        <th>Digitized points</th>\n",
       "        \n",
       "        <td>Not available</td>\n",
       "        \n",
       "    </tr>\n",
       "    <tr>\n",
       "        <th>Good channels</th>\n",
       "        <td>64 EEG</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "        <th>Bad channels</th>\n",
       "        <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "        <th>EOG channels</th>\n",
       "        <td>Not available</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "        <th>ECG channels</th>\n",
       "        <td>Not available</td>\n",
       "    \n",
       "    <tr>\n",
       "        <th>Sampling frequency</th>\n",
       "        <td>160.00 Hz</td>\n",
       "    </tr>\n",
       "    \n",
       "    \n",
       "    <tr>\n",
       "        <th>Highpass</th>\n",
       "        <td>0.00 Hz</td>\n",
       "    </tr>\n",
       "    \n",
       "    \n",
       "    <tr>\n",
       "        <th>Lowpass</th>\n",
       "        <td>80.00 Hz</td>\n",
       "    </tr>\n",
       "    \n",
       "    \n",
       "</table>"
      ],
      "text/plain": [
       "<Info | 7 non-empty values\n",
       " bads: []\n",
       " ch_names: Fc5., Fc3., Fc1., Fcz., Fc2., Fc4., Fc6., C5.., C3.., C1.., ...\n",
       " chs: 64 EEG\n",
       " custom_ref_applied: False\n",
       " highpass: 0.0 Hz\n",
       " lowpass: 80.0 Hz\n",
       " meas_date: 2009-08-12 16:15:00 UTC\n",
       " nchan: 64\n",
       " projs: []\n",
       " sfreq: 160.0 Hz\n",
       ">"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "raw.info"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e5b49a25-7964-416f-85b6-7e0b27639d9f",
   "metadata": {},
   "source": [
    "4. Launch Qt EEG viewer"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "d3e794f9-47cf-4872-a267-a47296519da4",
   "metadata": {
    "collapsed": true,
    "jupyter": {
     "outputs_hidden": true
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Using qt as 2D backend.\n",
      "Using pyopengl with version 3.1.6\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<mne_qt_browser._pg_figure.MNEQtBrowser at 0x287820af0>"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-08-09 16:22:24.001 python[5491:11275801] TSM AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 2462, in _select_annotations\n",
      "    self.weakmain()._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 2462, in _select_annotations\n",
      "    self.weakmain()._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py:346: RuntimeWarning: Error sending hover exit event:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 736, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/tornado/ioloop.py\", line 738, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 461, in advance_eventloop\n",
      "    eventloop(self)\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/ipykernel/eventloops.py\", line 128, in loop_qt\n",
      "    el.exec() if hasattr(el, 'exec') else el.exec_()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/pyqtgraph/widgets/GraphicsView.py\", line 343, in mouseReleaseEvent\n",
      "    super().mouseReleaseEvent(ev)\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py\", line 216, in mouseReleaseEvent\n",
      "    if self.sendDragEvent(ev, final=True):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py\", line 346, in sendDragEvent\n",
      "    debug.printExc(\"Error sending hover exit event:\")\n",
      "  --- exception caught here ---\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py\", line 344, in sendDragEvent\n",
      "    self.dragItem.mouseDragEvent(event)\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 1293, in mouseDragEvent\n",
      "    self.weakmain()._remove_region(\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4128, in _remove_region\n",
      "    self.mne.overview_bar.update_annotations()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 923, in update_annotations\n",
      "    annot_set = set([annot['onset'] for annot in annotations if\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 924, in <listcomp>\n",
      "    self.mne.visible_annotations[annot['description']]])\n",
      "KeyError: 'Te'\n",
      "  debug.printExc(\"Error sending hover exit event:\")\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py:346: RuntimeWarning: Error sending hover exit event:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 736, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/tornado/ioloop.py\", line 738, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 461, in advance_eventloop\n",
      "    eventloop(self)\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/ipykernel/eventloops.py\", line 128, in loop_qt\n",
      "    el.exec() if hasattr(el, 'exec') else el.exec_()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/pyqtgraph/widgets/GraphicsView.py\", line 343, in mouseReleaseEvent\n",
      "    super().mouseReleaseEvent(ev)\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py\", line 216, in mouseReleaseEvent\n",
      "    if self.sendDragEvent(ev, final=True):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py\", line 346, in sendDragEvent\n",
      "    debug.printExc(\"Error sending hover exit event:\")\n",
      "  --- exception caught here ---\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py\", line 344, in sendDragEvent\n",
      "    self.dragItem.mouseDragEvent(event)\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 1302, in mouseDragEvent\n",
      "    self.mne.overview_bar.update_annotations()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 923, in update_annotations\n",
      "    annot_set = set([annot['onset'] for annot in annotations if\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 924, in <listcomp>\n",
      "    self.mne.visible_annotations[annot['description']]])\n",
      "KeyError: 'Te'\n",
      "  debug.printExc(\"Error sending hover exit event:\")\n",
      "/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py:346: RuntimeWarning: Error sending hover exit event:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 736, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/tornado/ioloop.py\", line 738, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 461, in advance_eventloop\n",
      "    eventloop(self)\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/ipykernel/eventloops.py\", line 128, in loop_qt\n",
      "    el.exec() if hasattr(el, 'exec') else el.exec_()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/pyqtgraph/widgets/GraphicsView.py\", line 343, in mouseReleaseEvent\n",
      "    super().mouseReleaseEvent(ev)\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py\", line 216, in mouseReleaseEvent\n",
      "    if self.sendDragEvent(ev, final=True):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py\", line 346, in sendDragEvent\n",
      "    debug.printExc(\"Error sending hover exit event:\")\n",
      "  --- exception caught here ---\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py\", line 344, in sendDragEvent\n",
      "    self.dragItem.mouseDragEvent(event)\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 1293, in mouseDragEvent\n",
      "    self.weakmain()._remove_region(\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4128, in _remove_region\n",
      "    self.mne.overview_bar.update_annotations()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 923, in update_annotations\n",
      "    annot_set = set([annot['onset'] for annot in annotations if\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 924, in <listcomp>\n",
      "    self.mne.visible_annotations[annot['description']]])\n",
      "KeyError: 'Te'\n",
      "  debug.printExc(\"Error sending hover exit event:\")\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 3778, in _xrange_changed\n",
      "    self._update_regions_visible()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4229, in _update_regions_visible\n",
      "    if self.mne.visible_annotations[region.description]:\n",
      "KeyError: 'Test1'\n",
      "/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py:346: RuntimeWarning: Error sending hover exit event:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 736, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/tornado/ioloop.py\", line 738, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 461, in advance_eventloop\n",
      "    eventloop(self)\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/ipykernel/eventloops.py\", line 128, in loop_qt\n",
      "    el.exec() if hasattr(el, 'exec') else el.exec_()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/pyqtgraph/widgets/GraphicsView.py\", line 343, in mouseReleaseEvent\n",
      "    super().mouseReleaseEvent(ev)\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py\", line 216, in mouseReleaseEvent\n",
      "    if self.sendDragEvent(ev, final=True):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py\", line 346, in sendDragEvent\n",
      "    debug.printExc(\"Error sending hover exit event:\")\n",
      "  --- exception caught here ---\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py\", line 344, in sendDragEvent\n",
      "    self.dragItem.mouseDragEvent(event)\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 1302, in mouseDragEvent\n",
      "    self.mne.overview_bar.update_annotations()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 923, in update_annotations\n",
      "    annot_set = set([annot['onset'] for annot in annotations if\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 924, in <listcomp>\n",
      "    self.mne.visible_annotations[annot['description']]])\n",
      "KeyError: 'Te'\n",
      "  debug.printExc(\"Error sending hover exit event:\")\n",
      "/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py:346: RuntimeWarning: Error sending hover exit event:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 736, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/tornado/ioloop.py\", line 738, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 461, in advance_eventloop\n",
      "    eventloop(self)\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/ipykernel/eventloops.py\", line 128, in loop_qt\n",
      "    el.exec() if hasattr(el, 'exec') else el.exec_()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/pyqtgraph/widgets/GraphicsView.py\", line 343, in mouseReleaseEvent\n",
      "    super().mouseReleaseEvent(ev)\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py\", line 216, in mouseReleaseEvent\n",
      "    if self.sendDragEvent(ev, final=True):\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py\", line 346, in sendDragEvent\n",
      "    debug.printExc(\"Error sending hover exit event:\")\n",
      "  --- exception caught here ---\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py\", line 344, in sendDragEvent\n",
      "    self.dragItem.mouseDragEvent(event)\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 1293, in mouseDragEvent\n",
      "    self.weakmain()._remove_region(\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 4128, in _remove_region\n",
      "    self.mne.overview_bar.update_annotations()\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 923, in update_annotations\n",
      "    annot_set = set([annot['onset'] for annot in annotations if\n",
      "  File \"/Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py\", line 924, in <listcomp>\n",
      "    self.mne.visible_annotations[annot['description']]])\n",
      "KeyError: 'Te'\n",
      "  debug.printExc(\"Error sending hover exit event:\")\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Channels marked as bad:\n",
      "none\n"
     ]
    }
   ],
   "source": [
    "raw.plot(duration=10, n_channels=40, clipping=None)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5b579f63-8a51-4b60-ad6b-697719ad990e",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.16"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
